/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Route;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-12-04T04:27:57.615Z")

@Api(value = "route", description = "the route API")
public interface RouteApi {

    @ApiOperation(value = "", nickname = "routeGet", notes = "", response = Route.class, tags={ "route", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Route.class),
        @ApiResponse(code = 400, message = "Invalid Origin/Destination supplied"),
        @ApiResponse(code = 404, message = "Origin/Destination not found") })
    @RequestMapping(value = "/route",
        method = RequestMethod.GET)
    ResponseEntity<Route> routeGet(@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "origin", required = true) String origin,@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "destination", required = true) String destination);

}
